# Generated by Django 5.0.6 on 2025-01-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='salt',
        ),
    ]
